# Data Warehouse Admission Acute IP QA

In [24]:
import pandas as pd
import psycopg2
import sys
sys.path.append('H:/')
from uth_helpers.db_utils import get_dsn

In [25]:
connection = psycopg2.connect(get_dsn('dw.env', host='tacc')+' keepalives=1 keepalives_idle=30 keepalives_interval=10')
connection.autocommit = True

## Checking Counts of Admit table and Admit Claims Table

In [26]:
query = '''
select data_source, count(*) admit_row_count, count(distinct admit_id) admit_count, count(distinct uth_member_id) pat_count
from dev.gm_dw_ip_admit
group by 1
'''

admit_df = pd.read_sql(query, con=connection)
admit_df

C:\Users\iperez9\AppData\Local\Temp\3\ipykernel_17508\2853865154.py:7: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  admit_df = pd.read_sql(query, con=connection)

  data_source  admit_row_count  admit_count  pat_count
0        trum          2199770      2199770    1128390
1        mcrn          3702695      3702695    1357977
2        mcrt          5240465      5240465    1908029
3        iqva          7908321      7908321    4228237
4        truc          9660715      9660715    6604033

In [27]:
query = '''
select data_source, count(*) admit_row_count, count(distinct admit_id) admit_count, count(distinct uth_member_id) pat_count
from dev.gm_dw_ip_admit_claim
group by 1
'''

admit_claim_df = pd.read_sql(query, con=connection)
admit_claim_df

C:\Users\iperez9\AppData\Local\Temp\3\ipykernel_17508\2358596797.py:7: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  admit_claim_df = pd.read_sql(query, con=connection)

  data_source  admit_row_count  admit_count  pat_count
0        trum         33977833      2199770    1128390
1        mcrn         57310135      3702695    1357977
2        mcrt         84508357      5240465    1908029
3        iqva         84019124      7908321    4228237
4        truc         94797985      9660715    6604033

In [28]:
comp_df = pd.merge(left=admit_df, right=admit_claim_df, on='data_source')
comp_df

,data_source,admit_row_count_x,admit_count_x,pat_count_x,admit_row_count_y,admit_count_y,pat_count_y
0,trum,2199770,2199770,1128390,33977833,2199770,1128390
1,mcrn,3702695,3702695,1357977,57310135,3702695,1357977
2,mcrt,5240465,5240465,1908029,84508357,5240465,1908029
3,iqva,7908321,7908321,4228237,84019124,7908321,4228237
4,truc,9660715,9660715,6604033,94797985,9660715,6604033

Ideally, the number of unique admits should be the same in both tables. If it doesn't then we need to figure out if there is a significant difference between the two tables. This difference can happen due to the dates that are on the claims in both the detail and header levels.

In [29]:
comp_df['admit_count_same'] = comp_df['admit_count_x'] == comp_df['admit_count_y']
comp_df['pat_count_same'] = comp_df['pat_count_x'] == comp_df['pat_count_y']
comp_df[['admit_count_same', 'pat_count_same']]

   admit_count_same  pat_count_same
0              True            True
1              True            True
2              True            True
3              True            True
4              True            True

## Checking if there are any admissions episodes that overlap

Again, there shouldn't be any admissions that overlap with each other, but if there is, we need to investigate.

In [30]:
query ='''
select a.data_source, count(*) --a.admit_date as a_admit_dt, b.admit_date as b_admit_dt, b.discharge_date as b_discharge_date
from dev.gm_dw_ip_admit a 
inner join dev.gm_dw_ip_admit b
on a.uth_member_id = b.uth_member_id
and a.admit_date between b.admit_date+1 and b.discharge_date
group by 1
;
'''

pd.read_sql(query, con=connection)

C:\Users\iperez9\AppData\Local\Temp\3\ipykernel_17508\915520483.py:11: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  pd.read_sql(query, con=connection)

Empty DataFrame
Columns: [data_source, count]
Index: []

In [31]:
query ='''
select a.admit_date as a_admit_dt, a.discharge_date as a_discharge_dt, 
        b.admit_date as b_admit_dt, b.discharge_date as b_discharge_dt,
        a.admit_id, b.admit_id
from dev.gm_dw_ip_admit a 
inner join dev.gm_dw_ip_admit b
on a.uth_member_id = b.uth_member_id
and a.admit_date between b.admit_date+1 and b.discharge_date;
'''

pd.read_sql(query, con=connection)

C:\Users\iperez9\AppData\Local\Temp\3\ipykernel_17508\3683676966.py:11: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  pd.read_sql(query, con=connection)

Empty DataFrame
Columns: [a_admit_dt, a_discharge_dt, b_admit_dt, b_discharge_dt, admit_id, admit_id]
Index: []

## Checking Admission and Discharge Dates

Here we check the dates for admission and discharge to see if the dates are outside the initial range of years we generated the admit tables for.

In [32]:
query = '''
select data_source,
	sum(case when extract(year from admit_date) not between 2011 and 2024 then 1 else 0 end) as admit_oor,
	sum(case when extract(year from discharge_date) not between 2011 and 2024 then 1 else 0 end) as discharge_oor,
	sum(case when (discharge_date - admit_date) < 0 then 1 else 0 end ) as discharge_before_admit,
	count(*),
	sum(case when extract(year from admit_date) not between 2011 and 2024 then 1 else 0 end) * 1.0 / count(*) as admit_oor_pct,
	sum(case when extract(year from discharge_date) not between 2011 and 2024 then 1 else 0 end) * 1.0 / count(*) as discharge_oor_pct,
	sum(case when (discharge_date - admit_date) < 0 then 1 else 0 end ) * 1.0 / count(*) as discharge_before_admit_pct
from dev.gm_dw_ip_admit
group by data_source;
'''

pd.read_sql(query, con=connection)

C:\Users\iperez9\AppData\Local\Temp\3\ipykernel_17508\1917429032.py:14: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  pd.read_sql(query, con=connection)

,data_source,admit_oor,discharge_oor,discharge_before_admit,count,admit_oor_pct,discharge_oor_pct,discharge_before_admit_pct
0,truc,0,0,0,9660715,0.0,0.0,0.0
1,trum,0,0,0,2199770,0.0,0.0,0.0
2,iqva,0,0,0,7908321,0.0,0.0,0.0
3,mcrn,0,0,0,3702695,0.0,0.0,0.0
4,mcrt,0,0,0,5240465,0.0,0.0,0.0

In [ ]:
query = '''
select *
from dev.gm_dw_ip_admit
where extract(year from admit_date) not between 2011 and 2024;'''

pd.read_sql(query, con=connection)

In [34]:
query = '''
select *
from dev.gm_dw_ip_admit
where extract(year from discharge_date) not between 2011 and 2024;'''

pd.read_sql(query, con=connection)

C:\Users\iperez9\AppData\Local\Temp\3\ipykernel_17508\1592417387.py:6: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  pd.read_sql(query, con=connection)

Empty DataFrame
Columns: [data_source, uth_member_id, enc_id, admit_date, discharge_date, enc_discharge_status, admit_id, total_charge_amount, total_allowed_amount, total_paid_amount, missing_terminal_status, missing_terminal_status_117, paid_status, member_id_src, insert_ts]
Index: []

## Checking Bill Types at the beginning and end of an admit episode

In step 2, we added a column to determine whether during an admission episode had terminal bill codes (111, 114, 117) which indicate the start/end of an inpatient stay.

In [35]:
query = '''
select data_source, missing_terminal_status, count(*), 100.* count(*) / sum(count(*)) over (partition by data_source)
from dev.gm_dw_ip_admit
group by 1,2
order by 1,2;
'''

pd.read_sql(query, con=connection)

C:\Users\iperez9\AppData\Local\Temp\3\ipykernel_17508\1056602582.py:8: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  pd.read_sql(query, con=connection)

  data_source  missing_terminal_status    count   ?column?
0        iqva                    False  7861451  99.407333
1        iqva                     True    46870   0.592667
2        mcrn                    False  3698867  99.896616
3        mcrn                     True     3828   0.103384
4        mcrt                    False  5236713  99.928403
5        mcrt                     True     3752   0.071597
6        truc                    False  9317215  96.444363
7        truc                     True   343500   3.555637
8        trum                    False  2196463  99.849666
9        trum                     True     3307   0.150334

In [36]:
query = '''
select data_source, missing_terminal_status_117, count(*), 100.* count(*) / sum(count(*)) over (partition by data_source)
from dev.gm_dw_ip_admit
group by 1,2
order by 1,2;
'''

pd.read_sql(query, con=connection)

C:\Users\iperez9\AppData\Local\Temp\3\ipykernel_17508\1842700358.py:8: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  pd.read_sql(query, con=connection)

  data_source  missing_terminal_status_117    count   ?column?
0        iqva                        False  7697351  97.332304
1        iqva                         True   210970   2.667696
2        mcrn                        False  3660205  98.852457
3        mcrn                         True    42490   1.147543
4        mcrt                        False  5146734  98.211399
5        mcrt                         True    93731   1.788601
6        truc                        False  9380238  97.096726
7        truc                         True   280477   2.903274
8        trum                        False  2086409  94.846689
9        trum                         True   113361   5.153311

## Checking that total costs in admit table matches total cost in admit claims table

In [37]:
query = '''
with a as (
select a.*, total_allowed_amount, case when clm_total_allowed_amount != total_allowed_amount then 1 end as diff_allowed_flag
	, total_charge_amount, case when clm_total_charge_amount != total_charge_amount then 1 end as diff_charge_flag
	, total_paid_amount, case when clm_total_paid_amount != total_paid_amount then 1 end as diff_paid_flag
from 
	(select data_source, extract(year from admit_date) calendar_year , admit_id, sum(allowed_amount) clm_total_allowed_amount
													, sum(paid_amount) clm_total_paid_amount
													, sum(charge_amount) clm_total_charge_amount
	from dev.gm_dw_ip_admit_claim
	group by 1,2,3) a 
left join 
	(
		select data_source, extract(year from admit_date) calendar_year, admit_id, total_allowed_amount, total_paid_amount, total_charge_amount 
	 	from dev.gm_dw_ip_admit
) b 
on a.admit_id=b.admit_id and a.calendar_year=b.calendar_year and a.data_source = b.data_source
)
select data_source, count(*)
from a
where diff_allowed_flag = 1 
or diff_charge_flag = 1 
or diff_paid_flag = 1
group by 1
;'''

pd.read_sql(query, con=connection)

C:\Users\iperez9\AppData\Local\Temp\3\ipykernel_17508\3725402696.py:27: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  pd.read_sql(query, con=connection)

Empty DataFrame
Columns: [data_source, count]
Index: []

## Other

Double checking that member_id_src and claim_id_src are filled in the tables.

In [38]:
query = '''
select data_source, count(*)
from dev.gm_dw_ip_admit
where member_id_src is null or member_id_src = ''
group by 1'''

pd.read_sql(query, con=connection)

C:\Users\iperez9\AppData\Local\Temp\3\ipykernel_17508\3546408867.py:7: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  pd.read_sql(query, con=connection)

Empty DataFrame
Columns: [data_source, count]
Index: []

In [39]:
query = '''
select data_source, count(*)
from dev.gm_dw_ip_admit_claim
where member_id_src is null or member_id_src = ''
or claim_id_src is null or claim_id_src = ''
group by 1'''

pd.read_sql(query, con=connection)

C:\Users\iperez9\AppData\Local\Temp\3\ipykernel_17508\4077572481.py:8: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  pd.read_sql(query, con=connection)

Empty DataFrame
Columns: [data_source, count]
Index: []